spring:
  config:
    activate:
      on-profile: datasource

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/pickly?zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    open-in-view: false
